"""
Audio router — TTS narration + podcast script generation.

Endpoints:
  POST /audio/narrate          → MP3 bytes (audio/mpeg)
  POST /audio/podcast-script   → JSON segments for client-side podcast playback
"""
import logging

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response

from app.schemas.audio import (
    NarrateRequest,
    PodcastScriptRequest,
    PodcastScriptResponse,
)
from app.services import audio_service
from app.deps import get_current_user

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/audio", tags=["audio"])


def _audio_media_type(data: bytes) -> str:
    if len(data) >= 4 and data[:4] == b"RIFF":
        return "audio/wav"
    return "audio/mpeg"


@router.post("/narrate", summary="Convert text to MP3 audio")
def narrate_text(
    body: NarrateRequest,
    current_user=Depends(get_current_user),
) -> Response:
    """
    Accepts up to 5 000 characters of plain or Markdown text and returns
    audio bytes (MP3 from OpenAI TTS, or MP3/WAV from Manus when MANUS_API_KEY is set).
    """
    try:
        mp3_bytes = audio_service.text_to_speech(body.text, body.voice)
    except Exception as exc:
        logger.exception("TTS generation failed")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"TTS generation failed: {exc}",
        ) from exc

    media = _audio_media_type(mp3_bytes)
    logger.info(
        "tts_generated bytes=%s voice=%s media=%s", len(mp3_bytes), body.voice, media
    )
    return Response(content=mp3_bytes, media_type=media)


@router.post(
    "/podcast-script",
    response_model=PodcastScriptResponse,
    summary="Generate a two-host podcast discussion script",
)
def generate_podcast(
    body: PodcastScriptRequest,
    current_user=Depends(get_current_user),
) -> PodcastScriptResponse:
    """
    Uses GPT to produce a 10–14-segment two-host discussion about the book.
    The client is expected to call /audio/narrate for each segment in sequence.
    """
    try:
        data = audio_service.generate_podcast_script(
            summary_text=body.summary_text,
            title=body.title,
            author=body.author,
        )
    except Exception as exc:
        logger.exception("Podcast script generation failed")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Podcast script generation failed: {exc}",
        ) from exc

    return PodcastScriptResponse(**data)
